package by.epam.epamlab.controllers;

public enum TransportationActions {
	STARTING_TRANSPORTATION, COMPLETION_TRANSPORTATION,
	ABORTING_TRANSPORTATION, MOVING_ELEVATOR,
	BOARDING_OF_PASSENGER, DEBOARDING_OF_PASSENGER, VALIDATION;
}
