package by.epam.epamlab.controllers;

public enum TransportationTask {
	STARTING_TRANSPORTATION, COMPLETION_TRANSPORTATION, ABORTING_TRANSPORTATION,
	MOVING_ELEVATOR, BOADING_OF_PASSENGER, DEBOADING_OF_PASSENGER
}
